a=input('what are you name?')
b=input('what are you name?')
c=input('what are you name?')
d=float(input(a))
e=float(input(b))
f=float(input(c))
print(a,'is',d)
print(b,'is',e)
print(c,'is',f)
print(':|>')