l = ['Ahmad','Milad','Ashkan','Mohamad','Saeed','Dariush']
a = input('name: ')
a2 = int(input())
b = input('name: ')
b2 = int(input())
c = input('name: ')
c2 = int(input())
l.insert(a2,a)
l.insert(b2,b)
l.insert(c2,c)
print(l)